CREATE TYPE typeOfFormat AS ENUM ('pdf', 'docx', 'xsl', 'ppt', 'html', 'mp4');
create table documents (
	id INTEGER primary key generated by default as identity,
	name text not null,
	partNum text,
	verNum INTEGER not null,
	formatType typeOfFormat not null,
	relDate TIMESTAMP not null default now(),
	descr text,
	author text not null,
	productId INTEGER references products(id) on delete cascade not null,
	path text not null
	);